# Generated by Django 4.0.5 on 2022-07-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_message_body_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='xmedia'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.profile')),
            ],
            options={
                'ordering': ('-time_sent',),
            },
        ),
    ]
