# Generated by Django 4.0.5 on 2022-07-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.profile'),
        ),
    ]
