# Generated by Django 4.0.5 on 2022-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_notification_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.CharField(default='not set', max_length=1000),
        ),
    ]
