# Generated by Django 4.0.5 on 2022-07-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_profile',
        ),
    ]
