# Generated by Django 4.0.5 on 2022-07-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_notification_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.profile'),
        ),
    ]
