# Generated by Django 4.0.5 on 2022-07-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_latest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
