# Generated by Django 4.0.5 on 2022-07-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_latest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='test',
        ),
    ]
