# Generated by Django 4.0.5 on 2022-07-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_privatemessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='link',
        ),
    ]
