# Generated by Django 4.0.5 on 2022-07-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_privatemessage_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('name',)},
        ),
    ]
